service:
  name: telegram-pin-stack-bot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: 
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    AWS_DYNAMODB_NAME: telegram-pin-stack-bot
    AWS_DYNAMODB_REGION: eu-central-1


functions:
  telegram-pin-stack-bot:
    handler: index.handler
    events:
      - http: 
          method: post
          path: ack
